repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        language: python
        language_version: python3.11
        args: ["--config", "pyproject.toml", "--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0
    hooks:
      - id: mypy
        language: python
        language_version: python3.11
        args: ["--config-file", "pyproject.toml"]
        exclude: "tests/|venv/|\\.venv/|alembic/|migrations/"
        files: app/
        additional_dependencies:
         - pydantic
         - pydantic-settings
         - types-redis
         - types-pytz